### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by lovejoy** [BaiduPS/tera#18]
猜测是执行build.sh ?
libsofa-pbrpc.a(buffer.o):(.data.rel.ro._ZTVN4sofa5pbrpc11WriteBufferE[_ZTVN4sofa5pbrpc11WriteBufferE]+0x38)：对‘google::protobuf::io::ZeroCopyOutputStream::WriteAliasedRaw(void const*, int)’未定义的引用
libsofa-pbrpc.a(gzip_stream.o):(.data.rel.ro._ZTVN4sofa5pbrpc30AbstractCompressedOutputStreamE[_ZTVN4sofa5pbrpc30AbstractCompressedOutputStreamE]+0x38)：对‘google::protobuf::io::ZeroCopyOutputStream::WriteAliasedRaw(void const*, int)’未定义的引用
libsofa-pbrpc.a(gzip_stream.o):(.data.rel.ro._ZTVN4sofa5pbrpc16GzipOutputStreamE[_ZTVN4sofa5pbrpc16GzipOutputStreamE]+0x38)：对‘google::protobuf::io::ZeroCopyOutputStream::WriteAliasedRaw(void const*, int)’未定义的引用
libsofa-pbrpc.a(block_wrappers.o):(.data.rel.ro._ZTVN4sofa5pbrpc28BlockCompressionOutputStreamE[_ZTVN4sofa5pbrpc28BlockCompressionOutputStreamE]+0x38)：对‘google::protobuf::io::ZeroCopyOutputStream::WriteAliasedRaw(void const*, int)’未定义的引用
libsofa-pbrpc.a(block_wrappers.o):(.data.rel.ro._ZTVN4sofa5pbrpc18SnappyOutputStreamE[_ZTVN4sofa5pbrpc18SnappyOutputStreamE]+0x38)：对‘google::protobuf::io::ZeroCopyOutputStream::WriteAliasedRaw(void const*, int)’未定义的引用
libsofa-pbrpc.a(block_wrappers.o):(.data.rel.ro._ZTVN4sofa5pbrpc15LZ4OutputStreamE[_ZTVN4sofa5pbrpc15LZ4OutputStreamE]+0x38): more undefined references to `google::protobuf::io::ZeroCopyOutputStream::WriteAliasedRaw(void const*, int)' follow
collect2: error: ld returned 1 exit status
make: *** [sofa-pbrpc-client] 错误 1
另外build.sh 写的太挫

**Comment by bluebore** [comment]
build.sh康仔写了一天内呢，现在已经冲向你的工位了~
依赖库这块确实比较麻烦，我们正在搞

**Comment by 00k** [comment]
应该是依赖库的问题，build.sh会帮你把依赖下下来安装，但google的几个库（比如snappy、protobuf）从国内下载有很大的几率会失败，你可以找HK的机器试试。
另外提供了一种让开发者自己管理依赖库（库的下载地址可以参考build.sh）的编译方式，只要在depend.mk里指定库的安装路径，然后执行
sh build_version.sh
make proto
make -j4
就可以了。先试试看，有问题再反馈。

**Comment by lovejoy** [comment]
试了下sofa-pbrpc就编译不过去了，build.sh最大的问题是异常了都不退出还继续往下，让我以为成功了，结果一看，老早失败了。

**Comment by 00k** [comment]
以改进。公司内编译，推荐internal_build.sh。请试试看。

**Comment by 00k** [comment]
一些在国内下载困难的依赖库都换成github地址了，现在编译几乎不成问题了，我先close了 ; )
