### ISSUE TITLE
TERA 不就是HBase的C  版本吗！

### ISSUE THREAD

**Issue by wangan** [BaiduPS/tera#24]
TERA 不就是HBase的C++  版本吗！

**Comment by xupeilin** [comment]
ما كنت ترغب في التعبير

**Comment by 00k** [comment]
a. 全序数据库既是io bound也是cpu bound，tera的目标之一是高性能，因此语言很重要
b. tera和hbase在设计和实现上均有明显差异，举个例子：locality_group方面
c. tera是有大公司背书的生产系统，这点是与hbase最大的不同
暂时只能想到这么多了
