### ISSUE TITLE
系统是否也可以发布二进制版本

### ISSUE THREAD

**Issue by blackfox1983** [BaiduPS/tera#29]
1、源代码安装
2、二进制安装

**Comment by 00k** [comment]
二进制安装只在公司内部可行。
毕竟linux的发行版太多，暂时没有经历一个一个去搞。

**Comment by blackfox1983** [comment]
那就发行一个基础的版本。比如centos xx版本的。编译出来一个。
现在我这边有需求了。希望这么用。
