### ISSUE TITLE
BUILD说明可以更专业化一些

### ISSUE THREAD

**Issue by blackfox1983** [BaiduPS/tera#30]
1、依赖哪些外部基础库。
2、这些基础库的下载地址直接给出
3、依赖库是否有版本要求。比如pb是否可以使用pb3.
4、完整的安装过程示例以及结果提示。
      如configure --help 。安装到哪儿、成功是什么样子的。
5、系统如何启动。
6、系统如何控制。

**Comment by bluebore** [comment]
我也提个，建议写成Markdown格式的@李康

**Comment by 00k** [comment]
working on it ...

**Comment by 00k** [comment]
done, please review

**Comment by blackfox1983** [comment]
看到了。比原来的清晰、条理化多了。赞一个！
