### ISSUE TITLE
客户端sdk可以不包括任何编译依赖

### ISSUE THREAD

**Issue by blackfox1983** [BaiduPS/tera#37]
比如用户使用pb3，但是sdk和tera内部使用pb2.
这就影响用户使用了。
这块速度解决下把。

**Comment by 00k** [comment]
sdk依赖什么版本是由用户决定的，当然前提是sdk兼容这个版本。
用户使用pb3，那么编译tera的时候也在pb3环境下进行就可以了。记住libtera.a始终是由用户直接编译的，不是我们放出的。
tera现在没有对依赖库的兼容性做过测试，如果你有特殊的版本要求，可以提出来。

**Comment by blackfox1983** [comment]
我的意思是 直接提供一个二进制的server版本。（当然也可以提供src编译版本)
对应二进制版本的server，提供一个与任何第三方库没依赖的client lib。
类似于mysql一样。
版本依赖问题，让用户发现了，再修复。有些晚。
这些问题越早解决越好。

**Comment by 00k** [comment]
“与任何第三方库没依赖的client lib”，是指所有的依赖库都打包进来？

**Comment by blackfox1983** [comment]
以下均可接受：
1、如果可以不依赖于第三方库，类似mysql client这种的，直接提供库lib即可。
2、如果依赖第三方库，明确依赖的版本即可。如指定版本1.0.0；范围版本，2.0.0版本+……

**Comment by 00k** [comment]
当前支持第二种
