### ISSUE TITLE
既然开源，技术文档可以多讲下设计原因。

### ISSUE THREAD

**Issue by blackfox1983** [BaiduPS/tera#38]
一些地方直接就给出个结论。

**Comment by blackfox1983** [comment]
比如可以引申出其他类似系统相对于tera的短板。让大家知道选这个系统的好处。从用户角度出发， 在竞品中有优势，满足需求是第一位的，其次才是看内部实现。

**Comment by xupeilin** [comment]
这个会慢慢整理
结论不能直接给出，所有短板都是有背景条件的
应用场景的总结我们正在做，比如在什么场景下给出一份指导配置
