### ISSUE TITLE
代码需要增加注释。

### ISSUE THREAD

**Issue by blackfox1983** [BaiduPS/tera#39]
不论是内部编码规范还是开源实现。尤其是G家的开源实现。
代码注释往往比代码都多。尤其是.h文件中。

**Comment by bluebore** [comment]
这个真心比较难，慢慢来吧~

**Comment by 00k** [comment]
如果注释是用来描述代码的，那规范的代码本身比注释更容易被程序员理解
如果注释是用来描述设计的，那么还是用文档的形式表现出来会更好，毕竟会更集中、更抽象
所以我认为有两个地方需要注释，一是算法非常复杂，看代码不容易理解；二是对API的描述
其他情况下注释都可以用代码或文档取代
头文件中大段的注释可能只是把文档写在了代码中
你觉得呢

**Comment by blackfox1983** [comment]
可以接受。系统设计一般不放在代码中。单独列出比较合适。
对于代码中的注释，更多于接口功能说明。(*.h)
对于实现的注释，可以是较复杂逻辑的背景原因解释。(*.cpp)

**Comment by 00k** [comment]
好的，后面我们会按照这个原则进行开发
