### ISSUE TITLE
tera.flag这个magic file一直没出现。

### ISSUE THREAD

**Issue by blackfox1983** [BaiduPS/tera#46]
编译后没法启动。连-h都没法用。

**Comment by xupeilin** [comment]
单机试用版环境正在搭建中。。本周内给出

**Comment by xupeilin** [comment]
单机版已经给出，搭建方法在wiki中给出
https://github.com/BaiduPS/tera/wiki/%E9%97%AA%E7%94%B5%E4%BD%93%E9%AA%8CTera

tera.flag不是magic file...
