### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [BaiduPS/tera#5]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [HashClient](https://github.com/BaiduPS/tera/blob/59507d450c135e77b1b80b72c196d0ecd7dea146/tera/sdk/tera_hash.cc#L57 "destructor for HashClient")
* [MasterImpl](https://github.com/BaiduPS/tera/blob/59507d450c135e77b1b80b72c196d0ecd7dea146/tera/master/master_impl.cc#L125 "destructor for MasterImpl")
* [MemTableOnLevelDB](https://github.com/BaiduPS/tera/blob/59507d450c135e77b1b80b72c196d0ecd7dea146/tera/leveldb/db/memtable_on_leveldb.cc#L44 "destructor for MemTableOnLevelDB")
* [TableImpl](https://github.com/BaiduPS/tera/blob/59507d450c135e77b1b80b72c196d0ecd7dea146/tera/sdk/tera_easy.cc#L36 "destructor for TableImpl")

**Comment by taocp** [comment]
:good:

**Comment by elfring** [comment]
Thanks for [your small source improvement](https://github.com/BaiduPS/tera/commit/da242918079efe4af5d0df5751dbca080cc308d0 "Deletion of unnecessary null pointer checks").

**Comment by elfring** [comment]
Were a few update candidates left over?
* [BuildTable](https://github.com/baidu/tera/blob/a1614a35d2c2145fe0fa5b297070ef99650aacea/src/leveldb/db/builder.cc#L89 "BuildTable function")
* [HashClient](https://github.com/baidu/tera/blob/d1ccc04d9cf1c84a376c9a936167910a6df98db5/src/sdk/tera_hash.cc#L57 "Destructor for HashClient")
* [LRUCacheDeleter](https://github.com/baidu/tera/blob/af82f3cc09d8866264751f71a3694dcab9c214f1/src/io/tablet_scanner.cc#L31 "LRUCacheDeleter function")
