### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [BaiduPS/tera#6]
Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialise a mutex.") ⇒ [Mutex constructor](https://github.com/BaiduPS/tera/blob/1dbb0f542088fcf6314fd843d6cfea8f66c239d6/common/mutex.h#L23)
- [pthread_cond_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html "Wait on a condition.") ⇒ [CondVar::Wait](https://github.com/BaiduPS/tera/blob/1dbb0f542088fcf6314fd843d6cfea8f66c239d6/common/mutex.h#L113)

**Comment by bluebore** [comment]
Fixed, thanks for your review.

**Comment by elfring** [comment]
Are there a few update candidates left over?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream.") ⇒ [DumpResponse](https://github.com/baidu/tera/blob/af82f3cc09d8866264751f71a3694dcab9c214f1/src/monitor/teramo_main.cc#L311)
- [signal](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html "Signal management") ⇒ [main](https://github.com/baidu/tera/blob/af82f3cc09d8866264751f71a3694dcab9c214f1/src/tera_main.cc#L42)
