### ISSUE TITLE
readme描述可能导致的误解

### ISSUE THREAD

**Issue by taocp** [BaiduPS/tera#72]
https://github.com/BaiduPS/tera/blob/master/README.md#L32 (系统依赖 “使用分布式文件系统（HDFS、NFS等）持久化数据与元信息” 这一句）

此处的NFS是指baidu私有的nfs，
公众看到”NFS“可能首先会联想到同样是分布式文件系统的[NFS](https://www.google.com/#newwindow=1&q=nfs).
会不会造成歧义？如果是，建议把“NFS"这个词删掉。

另外，感觉是不是还需要说明下，代码里虽然有适配nfs文件系统的地方，但那个nfs是百度自研的系统，不是sun的那个。
免得用户鼓捣半天以为tera可以构建在sun的那个NFS上。

**Comment by xupeilin** [comment]
有道理，觉得可以改

**Comment by bluebore** [comment]
tera为什么不能建在sun的NFS上呢？

**Comment by taocp** [comment]
要做的话，应该也可以试一试。。。
我的意思是可能造成误解，比如拿现有的代码直接往sun的NFS上放，应该不work吧？
还是说baidu的NFS兼容了sun的NFS接口，所以tera在sun的NFS上也是work的？

**Comment by bluebore** [comment]
应该也可以?
动手试一试吧!

**Comment by taocp** [comment]
好的！

**Comment by taocp** [comment]
找了一些资料：
http://www.redhat.com/magazine/008jun05/features/gfs_nfs/
https://www.howtoforge.com/setting-up-an-nfs-server-and-client-on-centos-6.3

如果有可用的sun-nfs，在客户端将sun-nfs文件系统mount成功以后，即可像读写本地文件系统那样对sun-nfs进行读写。
因为安装sun-nfs、执行mount都需要root权限，我就没有进一步尝试了。。。
（如果有机器给我root权限，我可以实际跑一把 =。=）

我的看法：
1. sun-nfs这种分布式（网络）文件系统和 GFS/HDFS 等系统不同，前者尽量表现得像本地文件系统（尽管还有一些不足），没有多副本容灾等机制； GFS系列的文件系统很注重支持海量数据的场景，有很强的容错能力。
1. tera所依赖的dfs属于GFS系列的文件系统（至少需要dfs来保证持久化数据的多副本）；对于sun-nfs这类文件系统，最多只能作为本地文件系统来使用。
