### ISSUE TITLE
文档有一点不准确的地方

### ISSUE THREAD

**Issue by taocp** [BaiduPS/tera#77]
https://github.com/BaiduPS/tera/blob/master/doc/a_brief_intro_of_tera_(in_chinese).pdf

1. 序号有点乱，不信看目录
1. 4.1.1表格管理中，信息有误，tera目前没有使用root -> meta -> user tablets三层结构，而是meta -> user tablets.

**Comment by yoyzhou** [comment]
好的，不过先这样吧，我后面改成md把。你们就可以修改了。

**Comment by taocp** [comment]
嗯嗯，谢啦！

**Comment by bluebore** [comment]
后面更新了再关闭这个issue吧

**Comment by yoyzhou** [comment]
close it, please see pr #86
